### PR TITLE
Add a security policy

### PR DESCRIPTION
**Pull request by erkinalp**

### CODE REVIEW

**Comment by Flam3rboy** [comment]
Stop refering to me as the only hoster. Please refer to the fosscord organization in general and our development discord.

**Comment by erkinalp** [comment]
@Flam3rboy done

**Review by Intevel — APPROVED** [review]

**Review by TheArcaneBrony — APPROVED** [review]
Looks good to me.

**Review by ChrisChrome — APPROVED** [review]

**Comment by Thesourtimes** [comment]
Looks good to me either.

**Review by Thesourtimes — APPROVED** [review]

**Review by xNaCly — APPROVED** [review]

**Review by Flam3rboy — APPROVED** [review]

**Pull request merged**
